// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for a draft follow-up scratch
 */
export type DraftFollowUpData = { message: string, variant: string | null, };
