// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueuedMessage } from "./QueuedMessage";

/**
 * Status of the queue for a session (for frontend display)
 */
export type QueueStatus = { "status": "empty" } | { "status": "queued", message: QueuedMessage, };
