#!/bin/bash
echo "Setting up local SonarQube Server..."
echo "The recommended way to run SonarQube locally is via Docker:"
echo "  cd docker/compose"
echo "  docker-compose -f docker-compose.dev.yml up -d sonarqube"
echo ""
echo "To install SonarQube manually without Docker:"
echo "1. Download SonarQube Community Edition from https://www.sonarsource.com/products/sonarqube/downloads/"
echo "2. Extract the zip file"
echo "3. Run bin/*/sonar.sh start"
