Write-Host "Setting up local SonarQube Server..."
Write-Host "The recommended way to run SonarQube locally is via Docker:"
Write-Host "  cd docker/compose"
Write-Host "  docker-compose -f docker-compose.dev.yml up -d sonarqube"
Write-Host ""
Write-Host "To install SonarQube manually without Docker:"
Write-Host "1. Download SonarQube Community Edition from https://www.sonarsource.com/products/sonarqube/downloads/"
Write-Host "2. Extract the zip file"
Write-Host "3. Run bin/windows-x86-64/StartSonar.bat"
