// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from GET /api/auth/user - returns the current user ID
 */
export type CurrentUserResponse = { user_id: string, };
