// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from GET /api/auth/token - returns the current access token
 */
export type TokenResponse = { access_token: string, expires_at: string | null, };
