// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CLI Detection Status
 *
 * For frontend display of CLI installation status
 */
export type CliDetectionStatus = { 
/**
 * CLI type ID
 */
cliTypeId: string, 
/**
 * CLI name
 */
name: string, 
/**
 * Display name
 */
displayName: string, 
/**
 * Is installed
 */
installed: boolean, 
/**
 * Version number (if installed)
 */
version: string | null, 
/**
 * Executable file path (if installed)
 */
executablePath: string | null, 
/**
 * Installation guide URL
 */
installGuideUrl: string | null, };
