// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CLI Type
 *
 * Corresponds to database table: cli_type
 */
export type CliType = { 
/**
 * Primary key ID, format: cli-{name}
 */
id: string, 
/**
 * Internal name, e.g., 'claude-code'
 */
name: string, 
/**
 * Display name, e.g., 'Claude Code'
 */
displayName: string, 
/**
 * Detection command, e.g., 'claude --version'
 */
detectCommand: string, 
/**
 * Installation command (optional)
 */
installCommand: string | null, 
/**
 * Installation guide URL
 */
installGuideUrl: string | null, 
/**
 * Config file path template, e.g., '~/.claude/settings.json'
 */
configFilePath: string | null, 
/**
 * Is system built-in
 */
isSystem: boolean, 
/**
 * Created timestamp
 */
createdAt: string, };
