// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create Terminal Request
 */
export type CreateTerminalRequest = { cliTypeId: string, modelConfigId: string, customBaseUrl: string | null, customApiKey: string | null, role: string | null, roleDescription: string | null, };
