// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrchestratorConfig } from "./OrchestratorConfig";
import type { TerminalConfig } from "./TerminalConfig";

/**
 * Create Workflow Request
 */
export type CreateWorkflowRequest = { 
/**
 * Project ID
 */
projectId: string, 
/**
 * Workflow name
 */
name: string, 
/**
 * Workflow description
 */
description: string | null, 
/**
 * Use slash commands
 */
useSlashCommands: boolean, 
/**
 * Slash command ID list (in order)
 */
commandPresetIds: Array<string> | null, 
/**
 * Main Agent configuration
 */
orchestratorConfig: OrchestratorConfig | null, 
/**
 * Error handling terminal configuration
 */
errorTerminalConfig: TerminalConfig | null, 
/**
 * Merge terminal configuration
 */
mergeTerminalConfig: TerminalConfig, 
/**
 * Target branch
 */
targetBranch: string | null, };
