// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Git Event
 *
 * Corresponds to database table: git_event
 */
export type GitEvent = { 
/**
 * Primary key ID
 */
id: string, 
/**
 * Associated workflow ID
 */
workflowId: string, 
/**
 * Associated terminal ID (optional)
 */
terminalId: string | null, 
/**
 * Git commit hash
 */
commitHash: string, 
/**
 * Git branch
 */
branch: string, 
/**
 * Commit message
 */
commitMessage: string, 
/**
 * Parsed metadata (JSON format)
 */
metadata: string | null, 
/**
 * Processing status
 */
processStatus: string, 
/**
 * Main Agent response (JSON format)
 */
agentResponse: string | null, 
/**
 * Created timestamp
 */
createdAt: string, 
/**
 * Processed timestamp
 */
processedAt: string | null, };
