// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Model Config
 *
 * Corresponds to database table: model_config
 */
export type ModelConfig = { 
/**
 * Primary key ID, format: model-{cli}-{name}
 */
id: string, 
/**
 * Associated CLI type ID
 */
cliTypeId: string, 
/**
 * Model internal name, e.g., 'sonnet'
 */
name: string, 
/**
 * Display name, e.g., 'Claude Sonnet'
 */
displayName: string, 
/**
 * API model ID, e.g., 'claude-sonnet-4-20250514'
 */
apiModelId: string | null, 
/**
 * Is default model
 */
isDefault: boolean, 
/**
 * Is official model
 */
isOfficial: boolean, 
/**
 * Created timestamp
 */
createdAt: string, 
/**
 * Updated timestamp
 */
updatedAt: string, };
