// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Main Agent Configuration
 */
export type OrchestratorConfig = { apiType: string, baseUrl: string, apiKey: string, model: string, };
