// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RepoWithTargetBranch = { targetBranch: string, id: string, path: string, name: string, displayName: string, setupScript: string | null, cleanupScript: string | null, copyFiles: string | null, parallelSetupScript: boolean, devServerScript: string | null, createdAt: Date, updatedAt: Date, };
