// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Slash Command Preset
 *
 * Corresponds to database table: slash_command_preset
 */
export type SlashCommandPreset = { 
/**
 * Primary key ID
 */
id: string, 
/**
 * Command name, e.g., '/write-code'
 */
command: string, 
/**
 * Command description
 */
description: string, 
/**
 * Prompt template
 */
promptTemplate: string | null, 
/**
 * Is system built-in
 */
isSystem: boolean, 
/**
 * Created timestamp
 */
createdAt: string, 
/**
 * Updated timestamp
 */
updatedAt: string, };
