// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal Log
 *
 * Corresponds to database table: terminal_log
 */
export type TerminalLog = { 
/**
 * Primary key ID
 */
id: string, 
/**
 * Associated terminal ID
 */
terminalId: string, 
/**
 * Log type
 */
logType: string, 
/**
 * Log content
 */
content: string, 
/**
 * Created timestamp
 */
createdAt: string, };
