// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal Configuration
 */
export type TerminalConfig = { cliTypeId: string, modelConfigId: string, customBaseUrl: string | null, customApiKey: string | null, };
