// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal
 *
 * Corresponds to database table: terminal
 */
export type Terminal = { 
/**
 * Primary key ID (UUID as String)
 */
id: string, 
/**
 * Associated workflow task ID
 */
workflowTaskId: string, 
/**
 * CLI type ID
 */
cliTypeId: string, 
/**
 * Model config ID
 */
modelConfigId: string, 
/**
 * Custom API Base URL
 */
customBaseUrl: string | null, 
/**
 * Custom API Key (encrypted storage)
 */
customApiKey: string | null, 
/**
 * Role, e.g., 'coder', 'reviewer', 'fixer'
 */
role: string | null, 
/**
 * Role description
 */
roleDescription: string | null, 
/**
 * Execution order within task
 */
orderIndex: number, 
/**
 * Status
 */
status: string, 
/**
 * OS process ID
 */
processId: number | null, 
/**
 * PTY session ID
 */
ptySessionId: string | null, 
/**
 * Associated vibe-kanban session ID
 */
vkSessionId: string | null, 
/**
 * Last Git commit hash
 */
lastCommitHash: string | null, 
/**
 * Last Git commit message
 */
lastCommitMessage: string | null, 
/**
 * Started timestamp
 */
startedAt: string | null, 
/**
 * Completed timestamp
 */
completedAt: string | null, 
/**
 * Created timestamp
 */
createdAt: string, 
/**
 * Updated timestamp
 */
updatedAt: string, };
