// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateRepo = { displayName?: string | null, setupScript?: string | null, cleanupScript?: string | null, copyFiles?: string | null, parallelSetupScript?: boolean | null, devServerScript?: string | null, };
