// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workflow
 *
 * Corresponds to database table: workflow
 */
export type Workflow = { 
/**
 * Primary key ID (UUID as String for compatibility)
 */
id: string, 
/**
 * Associated project ID
 */
projectId: string, 
/**
 * Workflow name
 */
name: string, 
/**
 * Workflow description
 */
description: string | null, 
/**
 * Status
 */
status: string, 
/**
 * Use slash commands
 */
useSlashCommands: boolean, 
/**
 * Enable main Agent
 */
orchestratorEnabled: boolean, 
/**
 * Main Agent API type: 'openai' | 'anthropic' | 'custom'
 */
orchestratorApiType: string | null, 
/**
 * Main Agent API Base URL
 */
orchestratorBaseUrl: string | null, 
/**
 * Main Agent API Key (encrypted storage)
 */
orchestratorApiKey: string | null, 
/**
 * Main Agent model
 */
orchestratorModel: string | null, 
/**
 * Enable error handling terminal
 */
errorTerminalEnabled: boolean, 
/**
 * Error handling terminal CLI ID
 */
errorTerminalCliId: string | null, 
/**
 * Error handling terminal model ID
 */
errorTerminalModelId: string | null, 
/**
 * Merge terminal CLI ID
 */
mergeTerminalCliId: string, 
/**
 * Merge terminal model ID
 */
mergeTerminalModelId: string, 
/**
 * Target branch
 */
targetBranch: string, 
/**
 * All terminals ready timestamp
 */
readyAt: string | null, 
/**
 * User confirmed start timestamp
 */
startedAt: string | null, 
/**
 * Completed timestamp
 */
completedAt: string | null, 
/**
 * Created timestamp
 */
createdAt: string, 
/**
 * Updated timestamp
 */
updatedAt: string, };
