// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workflow Command Association
 *
 * Corresponds to database table: workflow_command
 */
export type WorkflowCommand = { 
/**
 * Primary key ID
 */
id: string, 
/**
 * Associated workflow ID
 */
workflowId: string, 
/**
 * Associated preset ID
 */
presetId: string, 
/**
 * Execution order
 */
orderIndex: number, 
/**
 * Custom parameters (JSON format)
 */
customParams: string | null, 
/**
 * Created timestamp
 */
createdAt: string, };
