// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workflow Task
 *
 * Corresponds to database table: workflow_task
 */
export type WorkflowTask = { 
/**
 * Primary key ID (UUID as String)
 */
id: string, 
/**
 * Associated workflow ID
 */
workflowId: string, 
/**
 * Associated vibe-kanban task ID (optional)
 */
vkTaskId: string | null, 
/**
 * Task name
 */
name: string, 
/**
 * Task description
 */
description: string | null, 
/**
 * Git branch name
 */
branch: string, 
/**
 * Status
 */
status: string, 
/**
 * Task order
 */
orderIndex: number, 
/**
 * Started timestamp
 */
startedAt: string | null, 
/**
 * Completed timestamp
 */
completedAt: string | null, 
/**
 * Created timestamp
 */
createdAt: string, 
/**
 * Updated timestamp
 */
updatedAt: string, };
